spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/SpringBoard
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 4000
      # create: Spring Boot가 실행되면 테이블을 지우고 새로 만듭니다. 기존에 테이블에 저장된 데이터는 삭제됩니다.
      # create-drop: Spring Boot가 종료되면 테이블을 삭제합니다.
      # update: Entity 클래스와 DB 스키마를 비교하여 DB에 생성되지 않은 테이블, 칼럼을 추가하며 제거는 하지 않습니다.
      # validate: Entity 클래스와 DB 스키마를 비교하여 다르면 예외를 발생시킵니다.
      # none: 아무것도 실행하지 않습니다.